spring:
  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: FIT5120tp40


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
